var nombres = [
    'María Guadalupe',
    'María',
    'Juana',
    'María del Carmen',
    'Margarita',
    'Verónica',
    'Elizabeth',
    'Alejandra',
    'Leticia',
    'María Elena',
    'Gabriela',
    'María de los Ángeles',
    'Patricia',
    'Josefina',
    'María de Jesús',
    'Rosa María',
    'Rosa',
    'Alicia',
    'Teresa',
    'Francisca',
    'Adriana',
    'Yolanda',
    'Martha',
    'María Isabel',
    'Silvia',
    'José Luis',
    'Juan',
    'Miguel Ángel',
    'José',
    'Francisco',
    'Jesús',
    'Antonio',
    'Alejandro',
    'Pedro',
    'Juan Carlos',
    'Manuel',
    'Ricardo',
    'Daniel',
    'Fernando',
    'Jorge',
    'Roberto',
    'Carlos',
    'Andrés Manuel',
    'Eduardo',
    'Javier',
    'Miguel',
    'Martín',
    'Rafael',
    'Marco Antonio',
    'José Antonio',
];

var apellidos = [
    'González',
    'Muñoz',
    'Rojas',
    'Díaz',
    'Pérez',
    'Soto',
    'Contreras',
    'Silva',
    'Martínez',
    'Sepúlveda',
    'Morales',
    'Rodríguez',
    'López',
    'Fuentes',
    'Hernández',
    'Torres',
    'Araya',
    'Flores',
    'Espinoza',
    'Valenzuela',
    'Castillo',
    'Ramírez',
    'Reyes',
    'Gutiérrez',
    'Castro',
    'Vargas',
    'Álvarez',
    'Vásquez',
    'Tapia',
    'Fernández',
    'Sánchez',
    'Carrasco',
    'Gómez',
    'Cortés',
    'Herrera',
    'Núñez',
    'Jara',
    'Vergara',
    'Rivera',
    'Figueroa',
    'López',
    'García',
    'Miranda',
    'Bravo',
    'Vera',
    'Molina',
    'Vega',
    'Campos',
    'Sandoval',
    'Orellana'
];

var estados = [
    'Aguascalientes',
    'Baja California',
    'Baja California Sur',
    'Campeche',
    'Chiapas',
    'Chihuahua',
    'Coahuila',
    'Colima',
    'Ciudad de México',
    'Durango',
    'Guanajuato',
    'Guerrero',
    'Hidalgo',
    'Jalisco',
    'Michoacán',
    'Morelos',
    'México',
    'Nayarit',
    'Nuevo León',
    'Oaxaca',
    'Puebla',
    'Querétaro',
    'Quintana Roo',
    'San Luis Potosí',
    'Sinaloa',
    'Sonora',
    'Tabasco',
    'Tamaulipas',
    'Tlaxcala',
    'Veracruz',
    'Yucatán',
    'Zacatecas',
];

var productos = [
    'CHAMARRA F*UCK DIET - NO ES NO',
    'CHAMARRA AMOR MEXA',
    'CHAMARRA MÉXICO',
    'CHAMARRA DIAMANTE DE BRONCE',
    'CHAMARRA MIND - HEART',
    'CHAMARRA MILAGROS MEXA',
    'CHAMARRA MEXIC*N',
    'CHAMARRA MAGIA',
    'CHAMARRA MARIPOSA',
    'CHAMARRAS SOULMATE',
    'CHAMARRAS DETAILS MATTER',
    'CHAMARRAS NEVER GIVE UP',
    'CHAMARRAS COUPLE GOALS',
    'CHAMARRAS INFINITO',
    'CHAMARRAS TOGETHER STRONGER',
    'CHAMARRA MEXA',
    'CHAMARRA MUERTOS',
    'CHAMARRA MAESTRO',
    'CHAMARRA MAGUEY',
    'CHAMARRA BRIGADA HÉROES MÉXICO',
    'CHAMARRA XOLO',
    'CHAMARRA CDMX',
    'CHAMARRA VOCAMX',
    'CHAMARRA CORAZÓN, LEALTAD Y HUEVOS',
    'CHAMARRAS MAGIC COUPLE'
];